from distutils.core import setup

setup(
    name='BeagleEye',
    version='.01',
    packages=['env.lib.python2.7.distutils', 'env.lib.python2.7.encodings', 'env.lib.python2.7.site-packages.pip',
              'env.lib.python2.7.site-packages.pip.req', 'env.lib.python2.7.site-packages.pip.vcs',
              'env.lib.python2.7.site-packages.pip.utils', 'env.lib.python2.7.site-packages.pip.compat',
              'env.lib.python2.7.site-packages.pip.models', 'env.lib.python2.7.site-packages.pip._vendor',
              'env.lib.python2.7.site-packages.pip._vendor.distlib',
              'env.lib.python2.7.site-packages.pip._vendor.distlib._backport',
              'env.lib.python2.7.site-packages.pip._vendor.colorama',
              'env.lib.python2.7.site-packages.pip._vendor.html5lib',
              'env.lib.python2.7.site-packages.pip._vendor.html5lib.trie',
              'env.lib.python2.7.site-packages.pip._vendor.html5lib.filters',
              'env.lib.python2.7.site-packages.pip._vendor.html5lib.serializer',
              'env.lib.python2.7.site-packages.pip._vendor.html5lib.treewalkers',
              'env.lib.python2.7.site-packages.pip._vendor.html5lib.treeadapters',
              'env.lib.python2.7.site-packages.pip._vendor.html5lib.treebuilders',
              'env.lib.python2.7.site-packages.pip._vendor.lockfile',
              'env.lib.python2.7.site-packages.pip._vendor.progress',
              'env.lib.python2.7.site-packages.pip._vendor.requests',
              'env.lib.python2.7.site-packages.pip._vendor.requests.packages',
              'env.lib.python2.7.site-packages.pip._vendor.requests.packages.chardet',
              'env.lib.python2.7.site-packages.pip._vendor.requests.packages.urllib3',
              'env.lib.python2.7.site-packages.pip._vendor.requests.packages.urllib3.util',
              'env.lib.python2.7.site-packages.pip._vendor.requests.packages.urllib3.contrib',
              'env.lib.python2.7.site-packages.pip._vendor.requests.packages.urllib3.packages',
              'env.lib.python2.7.site-packages.pip._vendor.requests.packages.urllib3.packages.ssl_match_hostname',
              'env.lib.python2.7.site-packages.pip._vendor.packaging',
              'env.lib.python2.7.site-packages.pip._vendor._markerlib',
              'env.lib.python2.7.site-packages.pip._vendor.cachecontrol',
              'env.lib.python2.7.site-packages.pip._vendor.cachecontrol.caches',
              'env.lib.python2.7.site-packages.pip._vendor.pkg_resources',
              'env.lib.python2.7.site-packages.pip._vendor.pkg_resources.tests',
              'env.lib.python2.7.site-packages.pip.commands', 'env.lib.python2.7.site-packages.pip.operations',
              'env.lib.python2.7.site-packages.numpy', 'env.lib.python2.7.site-packages.numpy.ma',
              'env.lib.python2.7.site-packages.numpy.doc', 'env.lib.python2.7.site-packages.numpy.fft',
              'env.lib.python2.7.site-packages.numpy.lib', 'env.lib.python2.7.site-packages.numpy.core',
              'env.lib.python2.7.site-packages.numpy.f2py', 'env.lib.python2.7.site-packages.numpy.compat',
              'env.lib.python2.7.site-packages.numpy.linalg', 'env.lib.python2.7.site-packages.numpy.random',
              'env.lib.python2.7.site-packages.numpy.testing', 'env.lib.python2.7.site-packages.numpy.distutils',
              'env.lib.python2.7.site-packages.numpy.distutils.tests.gen_ext',
              'env.lib.python2.7.site-packages.numpy.distutils.tests.f2py_ext',
              'env.lib.python2.7.site-packages.numpy.distutils.tests.swig_ext',
              'env.lib.python2.7.site-packages.numpy.distutils.tests.pyrex_ext',
              'env.lib.python2.7.site-packages.numpy.distutils.tests.f2py_f90_ext',
              'env.lib.python2.7.site-packages.numpy.distutils.command',
              'env.lib.python2.7.site-packages.numpy.distutils.fcompiler',
              'env.lib.python2.7.site-packages.numpy.matrixlib', 'env.lib.python2.7.site-packages.numpy.polynomial',
              'env.lib.python2.7.site-packages.MySQLdb', 'env.lib.python2.7.site-packages.MySQLdb.constants',
              'env.lib.python2.7.site-packages.requests', 'env.lib.python2.7.site-packages.requests.packages',
              'env.lib.python2.7.site-packages.requests.packages.chardet',
              'env.lib.python2.7.site-packages.requests.packages.urllib3',
              'env.lib.python2.7.site-packages.requests.packages.urllib3.util',
              'env.lib.python2.7.site-packages.requests.packages.urllib3.contrib',
              'env.lib.python2.7.site-packages.requests.packages.urllib3.packages',
              'env.lib.python2.7.site-packages.requests.packages.urllib3.packages.ssl_match_hostname',
              'env.lib.python2.7.site-packages._markerlib', 'env.lib.python2.7.site-packages.setuptools',
              'env.lib.python2.7.site-packages.setuptools.tests', 'env.lib.python2.7.site-packages.setuptools.command',
              'env.lib.python2.7.site-packages.pkg_resources', 'env.lib.python2.7.site-packages.pkg_resources.tests',
              'env.lib.python2.7.site-packages.pkg_resources._vendor',
              'env.lib.python2.7.site-packages.pkg_resources._vendor.packaging', 'env.local.lib.python2.7.distutils',
              'env.local.lib.python2.7.encodings', 'env.local.lib.python2.7.site-packages.pip',
              'env.local.lib.python2.7.site-packages.pip.req', 'env.local.lib.python2.7.site-packages.pip.vcs',
              'env.local.lib.python2.7.site-packages.pip.utils', 'env.local.lib.python2.7.site-packages.pip.compat',
              'env.local.lib.python2.7.site-packages.pip.models', 'env.local.lib.python2.7.site-packages.pip._vendor',
              'env.local.lib.python2.7.site-packages.pip._vendor.distlib',
              'env.local.lib.python2.7.site-packages.pip._vendor.distlib._backport',
              'env.local.lib.python2.7.site-packages.pip._vendor.colorama',
              'env.local.lib.python2.7.site-packages.pip._vendor.html5lib',
              'env.local.lib.python2.7.site-packages.pip._vendor.html5lib.trie',
              'env.local.lib.python2.7.site-packages.pip._vendor.html5lib.filters',
              'env.local.lib.python2.7.site-packages.pip._vendor.html5lib.serializer',
              'env.local.lib.python2.7.site-packages.pip._vendor.html5lib.treewalkers',
              'env.local.lib.python2.7.site-packages.pip._vendor.html5lib.treeadapters',
              'env.local.lib.python2.7.site-packages.pip._vendor.html5lib.treebuilders',
              'env.local.lib.python2.7.site-packages.pip._vendor.lockfile',
              'env.local.lib.python2.7.site-packages.pip._vendor.progress',
              'env.local.lib.python2.7.site-packages.pip._vendor.requests',
              'env.local.lib.python2.7.site-packages.pip._vendor.requests.packages',
              'env.local.lib.python2.7.site-packages.pip._vendor.requests.packages.chardet',
              'env.local.lib.python2.7.site-packages.pip._vendor.requests.packages.urllib3',
              'env.local.lib.python2.7.site-packages.pip._vendor.requests.packages.urllib3.util',
              'env.local.lib.python2.7.site-packages.pip._vendor.requests.packages.urllib3.contrib',
              'env.local.lib.python2.7.site-packages.pip._vendor.requests.packages.urllib3.packages',
              'env.local.lib.python2.7.site-packages.pip._vendor.requests.packages.urllib3.packages.ssl_match_hostname',
              'env.local.lib.python2.7.site-packages.pip._vendor.packaging',
              'env.local.lib.python2.7.site-packages.pip._vendor._markerlib',
              'env.local.lib.python2.7.site-packages.pip._vendor.cachecontrol',
              'env.local.lib.python2.7.site-packages.pip._vendor.cachecontrol.caches',
              'env.local.lib.python2.7.site-packages.pip._vendor.pkg_resources',
              'env.local.lib.python2.7.site-packages.pip._vendor.pkg_resources.tests',
              'env.local.lib.python2.7.site-packages.pip.commands',
              'env.local.lib.python2.7.site-packages.pip.operations', 'env.local.lib.python2.7.site-packages.numpy',
              'env.local.lib.python2.7.site-packages.numpy.ma', 'env.local.lib.python2.7.site-packages.numpy.doc',
              'env.local.lib.python2.7.site-packages.numpy.fft', 'env.local.lib.python2.7.site-packages.numpy.lib',
              'env.local.lib.python2.7.site-packages.numpy.core', 'env.local.lib.python2.7.site-packages.numpy.f2py',
              'env.local.lib.python2.7.site-packages.numpy.compat',
              'env.local.lib.python2.7.site-packages.numpy.linalg',
              'env.local.lib.python2.7.site-packages.numpy.random',
              'env.local.lib.python2.7.site-packages.numpy.testing',
              'env.local.lib.python2.7.site-packages.numpy.distutils',
              'env.local.lib.python2.7.site-packages.numpy.distutils.tests.gen_ext',
              'env.local.lib.python2.7.site-packages.numpy.distutils.tests.f2py_ext',
              'env.local.lib.python2.7.site-packages.numpy.distutils.tests.swig_ext',
              'env.local.lib.python2.7.site-packages.numpy.distutils.tests.pyrex_ext',
              'env.local.lib.python2.7.site-packages.numpy.distutils.tests.f2py_f90_ext',
              'env.local.lib.python2.7.site-packages.numpy.distutils.command',
              'env.local.lib.python2.7.site-packages.numpy.distutils.fcompiler',
              'env.local.lib.python2.7.site-packages.numpy.matrixlib',
              'env.local.lib.python2.7.site-packages.numpy.polynomial', 'env.local.lib.python2.7.site-packages.MySQLdb',
              'env.local.lib.python2.7.site-packages.MySQLdb.constants',
              'env.local.lib.python2.7.site-packages.requests',
              'env.local.lib.python2.7.site-packages.requests.packages',
              'env.local.lib.python2.7.site-packages.requests.packages.chardet',
              'env.local.lib.python2.7.site-packages.requests.packages.urllib3',
              'env.local.lib.python2.7.site-packages.requests.packages.urllib3.util',
              'env.local.lib.python2.7.site-packages.requests.packages.urllib3.contrib',
              'env.local.lib.python2.7.site-packages.requests.packages.urllib3.packages',
              'env.local.lib.python2.7.site-packages.requests.packages.urllib3.packages.ssl_match_hostname',
              'env.local.lib.python2.7.site-packages._markerlib', 'env.local.lib.python2.7.site-packages.setuptools',
              'env.local.lib.python2.7.site-packages.setuptools.tests',
              'env.local.lib.python2.7.site-packages.setuptools.command',
              'env.local.lib.python2.7.site-packages.pkg_resources',
              'env.local.lib.python2.7.site-packages.pkg_resources.tests',
              'env.local.lib.python2.7.site-packages.pkg_resources._vendor',
              'env.local.lib.python2.7.site-packages.pkg_resources._vendor.packaging'],
    url='http://github.com/JavaWantaBe/BeagleEye',
    license='GPL',
    author='Richard Lowe',
    author_email='ocdrichard@gmail.com',
    description='License plate recognition for BeagleBone Black'
)
